apiVersion: v1
kind: Service
metadata:
  name: {{ template "cpa.fullname" . }}
  labels:
{{ include "cpa.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "cpa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
